# Generated by Django 2.1.3 on 2019-04-20 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_todo_finish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='finish',
            field=models.BooleanField(default=False),
        ),
    ]
